name: fad_cnc_app
description: FAD Market mobile application.
publish_to: "none"

version: 1.1.0+3
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  record: 6.2.1
  audioplayers: 6.6.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fce_logo.jpeg
    - assets/ai_assistant/fce_ai_frame_1.png
    - assets/ai_assistant/fce_ai_frame_2.png
    - assets/ai_assistant/fce_ai_frame_3.png
    - assets/ai_assistant/fce_ai_frame_4.png
    - assets/ai_assistant/fce_ai_frame_5.png
    - assets/ai_assistant/fce_ai_frame_6.png
